INPUT_LAYER_SIZE = 50 * 350

ALPHABET = [
    " ", # EMPTY
    "ᠸ", # MONGGOLIAN LETTER WA
    "ᡝ", # MONGGOLIAN LETTER SIBE E
    "ᡳ", # MONGGOLIAN LETTER MANCHU I
    "ᠯ", # MONGGOLIAN LETTER LA
    "ᠪ", # MONGGOLIAN LETTER BA
    "ᡩ", # MONGGOLIAN LETTER SIBE DA
    "ᡵ", # MONGGOLIAN LETTER MANCHU RA
    "ᠵ", # MONGGOLIAN LETTER JA
    "ᠠ", # MONGGOLIAN LETTER A
    "ᠩ", # MONGGOLIAN LETTER ANG
    "ᡤ", # MONGGOLIAN LETTER SIBE GA
    "ᠨ", # MONGGOLIAN LETTER NA
    "ᡴ", # MONGGOLIAN LETTER MANCHU KA
    "ᠴ", # MONGGOLIAN LETTER CHA
    "ᡠ", # MONGGOLIAN LETTER SIBE UE
    "ᡥ", # MONGGOLIAN LETTER SIBE HA
    "ᡡ", # MONGGOLIAN LETTER SIBE U
    "ᠮ", # MONGGOLIAN LETTER MA
    "ᠣ", # MONGGOLIAN LETTER O
    "ᡧ", # MONGGOLIAN LETTER SIBE SHA
    "ᡶ", # MONGGOLIAN LETTER MANCHU FA
    "ᠶ", # MONGGOLIAN LETTER YA
    "ᠰ", # MONGGOLIAN LETTER SA
    "ᡬ", # MONGGOLIAN LETTER SIBE GAA
    "ᡨ", # MONGGOLIAN LETTER SIBE TA
    "ᡰ", # MONGGOLIAN LETTER SIBE RAA
    "ᡦ", # MONGGOLIAN LETTER SIBE PA
    "᠈", # MONGGOLIAN MANCHU COMMA
    "᠉", # MONGGOLIAN MANCHU FULL STOP
    "ᠺ", # MONGGOLIAN LETTER KA
    "ᡮ", # MONGGOLIAN LETTER SIBE TSA
    "ᡟ", # MONGGOLIAN LETTER SIBE IY
    "ᡯ", # MONGGOLIAN LETTER SIBE ZA
    "ᡱ", # MONGGOLIAN LETTER SIBE CHA
    "ᡭ", # MONGGOLIAN LETTER SIBE HAA
    "", # MONGGOLIAN VOWEL SEPARATOR
    "ᡷ", # MONGGOLIAN LETTER MANCHU ZHA
    "\u180b", # MONGOLIAN FREE VARIATION SELECTOR ONE
]

WIDTH = 50
HEIGHT = 350
INPUT_LAYER_SIZE = WIDTH * HEIGHT
WORD_MAX_CHARACTERS = 30
CHARACTERS_IN_ALPHABET = len(ALPHABET)
OUTPUT_LAYER_SIZE = WORD_MAX_CHARACTERS * CHARACTERS_IN_ALPHABET

def pixel_string_to_array(string):
    array = [0] * INPUT_LAYER_SIZE
    for index in range(len(string)):
        char = string[index]
        if char == '1': array[index] = 1
    return array
