import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
			<header>
  			<nav>
					<ul>
						<li><Link href="/">Lexigraph Labelling</Link></li>
						<li><Link href="/lexigraphy">Lexigraphy</Link></li>
						<li><Link href="/training">Training</Link></li>
					</ul>
  			</nav>
			</header>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
